<?php

class MediumtermplanningsTableSeeder extends Seeder 
{
	
	public function run()
	{
		$mediumtermplannings = array(
			['module_id' => 1, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 1, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 1, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 1, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 2, 'turn_id' => 3, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 2, 'turn_id' => 5, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 2, 'turn_id' => 7, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 2, 'turn_id' => 9, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 3, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 3, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 3, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 3, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 4, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 4, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 4, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 4, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 16, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 16, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 16, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 16, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 15, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 15, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 15, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 15, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 11, 'turn_id' => 3, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 11, 'turn_id' => 5, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 11, 'turn_id' => 7, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 11, 'turn_id' => 9, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 17, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 17, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 17, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 17, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 5, 'turn_id' => 3, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 5, 'turn_id' => 5, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 5, 'turn_id' => 7, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 5, 'turn_id' => 9, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 6, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 6, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 6, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 6, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 9, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 9, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 9, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 9, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 22, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 22, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 22, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 22, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 8, 'turn_id' => 3, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 8, 'turn_id' => 5, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 8, 'turn_id' => 7, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 8, 'turn_id' => 9, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 42, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 42, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 42, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 42, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 45, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 45, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 45, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 45, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 62, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 62, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 62, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 62, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 65, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 65, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 65, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 65, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 66, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 66, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 66, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 66, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
		);
		
		DB::table('mediumtermplannings')->insert($mediumtermplannings);
	}
}
