<?php

class MediumtermplanningsTableSeeder extends Seeder {
	
	public function run()
	{
		$mediumtermplannings = array(
			['module_id' => 1, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 1, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 1, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 1, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 2, 'turn_id' => 3, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 2, 'turn_id' => 5, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 2, 'turn_id' => 7, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 2, 'turn_id' => 9, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 3, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 3, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 3, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 3, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 4, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 4, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 4, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 4, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 16, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 16, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 16, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 16, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 15, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 15, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 15, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 15, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 11, 'turn_id' => 3, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 11, 'turn_id' => 5, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 11, 'turn_id' => 7, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 11, 'turn_id' => 9, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 17, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 17, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 17, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 17, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 5, 'turn_id' => 3, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 5, 'turn_id' => 5, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 5, 'turn_id' => 7, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 5, 'turn_id' => 9, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 6, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 6, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 6, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 6, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 9, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 9, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 9, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 9, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 22, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 22, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 22, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 22, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 8, 'turn_id' => 3, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 8, 'turn_id' => 5, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 8, 'turn_id' => 7, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 8, 'turn_id' => 9, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 42, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 42, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 42, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 42, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 45, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 45, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 45, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 45, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 62, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 62, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 62, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 62, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 65, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 65, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 65, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 65, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 66, 'turn_id' => 4, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 66, 'turn_id' => 6, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 66, 'turn_id' => 8, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['module_id' => 66, 'turn_id' => 10, 'created_at' => new DateTime, 'updated_at' => new DateTime],
		);
		
		$employee_mediumtermplanning = array(
			['mediumtermplanning_id' => 1, 'employee_id' => 82, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 1, 'employee_id' => 83, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 2, 'employee_id' => 82, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 3, 'employee_id' => 82, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 4, 'employee_id' => 82, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 5, 'employee_id' => 82, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 5, 'employee_id' => 83, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 6, 'employee_id' => 82, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 6, 'employee_id' => 84, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 7, 'employee_id' => 82, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 8, 'employee_id' => 82, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 9, 'employee_id' => 27, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 10, 'employee_id' => 27, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 11, 'employee_id' => 27, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 12, 'employee_id' => 39, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 13, 'employee_id' => 14, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 14, 'employee_id' => 14, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 15, 'employee_id' => 14, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 16, 'employee_id' => 14, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 17, 'employee_id' => 52, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 17, 'employee_id' => 86, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 17, 'employee_id' => 85, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 18, 'employee_id' => 52, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 18, 'employee_id' => 86, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 18, 'employee_id' => 85, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 19, 'employee_id' => 52, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 19, 'employee_id' => 86, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 19, 'employee_id' => 85, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 20, 'employee_id' => 52, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 20, 'employee_id' => 86, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 20, 'employee_id' => 85, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 21, 'employee_id' => 87, 'semester_periods_per_week' => 3, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 22, 'employee_id' => 87, 'semester_periods_per_week' => 3, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 23, 'employee_id' => 87, 'semester_periods_per_week' => 3, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 24, 'employee_id' => 87, 'semester_periods_per_week' => 3, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 25, 'employee_id' => 88, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 25, 'employee_id' => 89, 'semester_periods_per_week' => 1, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 26, 'employee_id' => 88, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 26, 'employee_id' => 89, 'semester_periods_per_week' => 1, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 27, 'employee_id' => 88, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 27, 'employee_id' => 89, 'semester_periods_per_week' => 1, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 28, 'employee_id' => 88, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 28, 'employee_id' => 89, 'semester_periods_per_week' => 1, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 29, 'employee_id' => 91, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 30, 'employee_id' => 91, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 31, 'employee_id' => 91, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 32, 'employee_id' => 91, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 33, 'employee_id' => 92, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 34, 'employee_id' => 92, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 33, 'employee_id' => 52, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 34, 'employee_id' => 52, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 35, 'employee_id' => 52, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 36, 'employee_id' => 52, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 37, 'employee_id' => 93, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 37, 'employee_id' => 52, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 38, 'employee_id' => 93, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 38, 'employee_id' => 52, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 39, 'employee_id' => 93, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 39, 'employee_id' => 52, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 40, 'employee_id' => 93, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 40, 'employee_id' => 52, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 41, 'employee_id' => 92, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 41, 'employee_id' => 94, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 41, 'employee_id' => 95, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 42, 'employee_id' => 6, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 42, 'employee_id' => 95, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 42, 'employee_id' => 94, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 43, 'employee_id' => 6, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 43, 'employee_id' => 95, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 43, 'employee_id' => 94, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 44, 'employee_id' => 6, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 44, 'employee_id' => 95, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 44, 'employee_id' => 94, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 45, 'employee_id' => 84, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 46, 'employee_id' => 84, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 47, 'employee_id' => 84, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 48, 'employee_id' => 84, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 49, 'employee_id' => 6, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 50, 'employee_id' => 6, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 51, 'employee_id' => 6, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 52, 'employee_id' => 6, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 53, 'employee_id' => 52, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 53, 'employee_id' => 96, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 54, 'employee_id' => 52, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 54, 'employee_id' => 96, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 55, 'employee_id' => 52, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 55, 'employee_id' => 96, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 56, 'employee_id' => 52, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 56, 'employee_id' => 96, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 57, 'employee_id' => 85, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 57, 'employee_id' => 86, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 57, 'employee_id' => 52, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 58, 'employee_id' => 85, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 58, 'employee_id' => 86, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 58, 'employee_id' => 52, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 59, 'employee_id' => 85, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 59, 'employee_id' => 86, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 59, 'employee_id' => 52, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 60, 'employee_id' => 85, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 60, 'employee_id' => 86, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 60, 'employee_id' => 52, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 61, 'employee_id' => 95, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 62, 'employee_id' => 95, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 63, 'employee_id' => 95, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 64, 'employee_id' => 95, 'semester_periods_per_week' => 2, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 65, 'employee_id' => 95, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 65, 'employee_id' => 97, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 66, 'employee_id' => 95, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 66, 'employee_id' => 97, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 67, 'employee_id' => 95, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 67, 'employee_id' => 97, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 68, 'employee_id' => 95, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 68, 'employee_id' => 97, 'semester_periods_per_week' => 0, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 69, 'employee_id' => 95, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 70, 'employee_id' => 95, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 71, 'employee_id' => 95, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['mediumtermplanning_id' => 72, 'employee_id' => 95, 'semester_periods_per_week' => 4, 'annulled' => 0, 'created_at' => new DateTime, 'updated_at' => new DateTime],
		);
		
		DB::table('mediumtermplannings')->insert($mediumtermplannings);
		DB::table('employee_mediumtermplanning')->insert($employee_mediumtermplanning);
	}
}