<?php
use Illuminate\Database\Seeder;
class PlanningRoomTableSeeder extends Seeder
{
	public function run()
	{
		$planning_room = array(
			['planning_id' => 19, 'room_id' => 55,'weekday' => 3, 'start_time' => '08:00:00', 'end_time' => '10:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 1, 'room_id' => 38,'weekday' => 2, 'start_time' => '14:00:00', 'end_time' => '16:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 10, 'room_id' => 44,'weekday' => 1, 'start_time' => '12:00:00', 'end_time' => '14:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 10, 'room_id' => 44,'weekday' => 3, 'start_time' => '12:00:00', 'end_time' => '14:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 48, 'room_id' => 21,'weekday' => 3, 'start_time' => '16:00:00', 'end_time' => '18:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 20, 'room_id' => 44,'weekday' => 2, 'start_time' => '16:00:00', 'end_time' => '18:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 20, 'room_id' => 65,'weekday' => 4, 'start_time' => '12:00:00', 'end_time' => '14:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 54, 'room_id' => 49,'weekday' => 4, 'start_time' => '12:00:00', 'end_time' => '14:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 81, 'room_id' => 55,'weekday' => 4, 'start_time' => '15:00:00', 'end_time' => '17:30:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 82, 'room_id' => 3,'weekday' => 2, 'start_time' => '10:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 83, 'room_id' => 23,'weekday' => 2, 'start_time' => '10:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 84, 'room_id' => 24,'weekday' => 2, 'start_time' => '10:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 103, 'room_id' => 3,'weekday' => 2, 'start_time' => '10:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 2, 'room_id' => 12,'weekday' => 0, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 2, 'room_id' => 16,'weekday' => 0, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 2, 'room_id' => 5,'weekday' => 0, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 2, 'room_id' => 9,'weekday' => 0, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 2, 'room_id' => 10,'weekday' => 0, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 3, 'room_id' => 5,'weekday' => 0, 'start_time' => '13:00:00', 'end_time' => '16:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 3, 'room_id' => 9,'weekday' => 0, 'start_time' => '13:00:00', 'end_time' => '16:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 3, 'room_id' => 10,'weekday' => 0, 'start_time' => '13:00:00', 'end_time' => '16:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 3, 'room_id' => 12,'weekday' => 0, 'start_time' => '13:00:00', 'end_time' => '16:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 3, 'room_id' => 16,'weekday' => 0, 'start_time' => '13:00:00', 'end_time' => '16:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 4, 'room_id' => 12,'weekday' => 1, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 4, 'room_id' => 16,'weekday' => 1, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 4, 'room_id' => 5,'weekday' => 1, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 4, 'room_id' => 9,'weekday' => 1, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 4, 'room_id' => 10,'weekday' => 1, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 5, 'room_id' => 12,'weekday' => 1, 'start_time' => '14:00:00', 'end_time' => '17:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 5, 'room_id' => 16,'weekday' => 1, 'start_time' => '14:00:00', 'end_time' => '17:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 5, 'room_id' => 5,'weekday' => 1, 'start_time' => '14:00:00', 'end_time' => '17:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 5, 'room_id' => 9,'weekday' => 1, 'start_time' => '14:00:00', 'end_time' => '17:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 5, 'room_id' => 10,'weekday' => 1, 'start_time' => '14:00:00', 'end_time' => '17:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 6, 'room_id' => 11,'weekday' => 2, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 6, 'room_id' => 12,'weekday' => 2, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 6, 'room_id' => 16,'weekday' => 2, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 6, 'room_id' => 5,'weekday' => 2, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 6, 'room_id' => 9,'weekday' => 2, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 6, 'room_id' => 10,'weekday' => 2, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 7, 'room_id' => 15,'weekday' => 3, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 7, 'room_id' => 12,'weekday' => 3, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 7, 'room_id' => 16,'weekday' => 3, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 7, 'room_id' => 9,'weekday' => 3, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 7, 'room_id' => 10,'weekday' => 3, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 8, 'room_id' => 12,'weekday' => 3, 'start_time' => '14:00:00', 'end_time' => '17:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 8, 'room_id' => 15,'weekday' => 3, 'start_time' => '14:00:00', 'end_time' => '17:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 8, 'room_id' => 16,'weekday' => 3, 'start_time' => '14:00:00', 'end_time' => '17:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 8, 'room_id' => 9,'weekday' => 3, 'start_time' => '14:00:00', 'end_time' => '17:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 8, 'room_id' => 10,'weekday' => 3, 'start_time' => '14:00:00', 'end_time' => '17:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 9, 'room_id' => 5,'weekday' => 4, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 9, 'room_id' => 9,'weekday' => 4, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 9, 'room_id' => 10,'weekday' => 4, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 9, 'room_id' => 12,'weekday' => 4, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 9, 'room_id' => 16,'weekday' => 4, 'start_time' => '09:00:00', 'end_time' => '12:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 21, 'room_id' => 23,'weekday' => 0, 'start_time' => '12:00:00', 'end_time' => '13:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 22, 'room_id' => 27,'weekday' => 0, 'start_time' => '12:00:00', 'end_time' => '13:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
			['planning_id' => 23, 'room_id' => 23,'weekday' => 0, 'start_time' => '13:00:00', 'end_time' => '14:00:00', 'created_at' => new DateTime, 'updated_at' => new DateTime],
		);
		DB::table('planning_room')->insert($planning_room);
	}
}