<?php

use Illuminate\Database\Seeder;
class RoomsTableSeeder extends Seeder {
	
	public function run()
	{
		$rooms = array(
				['name' => 'B-201', 'Location' => 'Stellingen', 'seats' => 121, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 1],
				['name' => 'C-101', 'Location' => 'Stellingen', 'seats' => 15, 'roomtype_id' => 2, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 1],
				['name' => 'C-104', 'Location' => 'Stellingen', 'seats' => 15, 'roomtype_id' => 2, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 1],
				['name' => 'C-221', 'Location' => 'Stellingen', 'seats' => 30, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'D-010', 'Location' => 'Stellingen', 'seats' => 20, 'roomtype_id' => 3, 'beamer' => 1, 'blackboard' => 0, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'D-011', 'Location' => 'Stellingen', 'seats' => 6, 'roomtype_id' => 3, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-012', 'Location' => 'Stellingen', 'seats' => 6, 'roomtype_id' => 3, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-013', 'Location' => 'Stellingen', 'seats' => 6, 'roomtype_id' => 3, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-017', 'Location' => 'Stellingen', 'seats' => 16, 'roomtype_id' => 3, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-018', 'Location' => 'Stellingen', 'seats' => 12, 'roomtype_id' => 3, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-022', 'Location' => 'Stellingen', 'seats' => 8, 'roomtype_id' => 3, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-114', 'Location' => 'Stellingen', 'seats' => 10, 'roomtype_id' => 3, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-115', 'Location' => 'Stellingen', 'seats' => 6, 'roomtype_id' => 3, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-117', 'Location' => 'Stellingen', 'seats' => 6, 'roomtype_id' => 3, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-118/119', 'Location' => 'Stellingen', 'seats' => 12, 'roomtype_id' => 3, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-121', 'Location' => 'Stellingen', 'seats' => 6, 'roomtype_id' => 3, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-125', 'Location' => 'Stellingen', 'seats' => 40, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-129', 'Location' => 'Stellingen', 'seats' => 20, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'D-220', 'Location' => 'Stellingen', 'seats' => 30, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'F-009', 'Location' => 'Stellingen', 'seats' => 45, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'F-132', 'Location' => 'Stellingen', 'seats' => 80, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'F-235', 'Location' => 'Stellingen', 'seats' => 17, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'F-334', 'Location' => 'Stellingen', 'seats' => 25, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'F-534', 'Location' => 'Stellingen', 'seats' => 25, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'F-635', 'Location' => 'Stellingen', 'seats' => 20, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'P3-06', 'Location' => 'Stellingen', 'seats' => 18, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 0, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'P3-07', 'Location' => 'Stellingen', 'seats' => 18, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 0, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'P3-09', 'Location' => 'Stellingen', 'seats' => 12, 'roomtype_id' => 2, 'beamer' => 1, 'blackboard' => 0, 'overheadprojector' => 0, 'accessible' => 0],
				['name' => 'R-031', 'Location' => 'Stellingen', 'seats' => 20, 'roomtype_id' => 2, 'beamer' => 0, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Geom H1', 'Location' => 'Geomatikum', 'seats' => 348, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Geom H2', 'Location' => 'Geomatikum', 'seats' => 194, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Geom H3', 'Location' => 'Geomatikum', 'seats' => 60, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Geom H4', 'Location' => 'Geomatikum', 'seats' => 123, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Geom H5', 'Location' => 'Geomatikum', 'seats' => 85, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Geom H6', 'Location' => 'Geomatikum', 'seats' => 114, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Grindel 48,HS', 'Location' => 'Grindel 48', 'seats' => 69, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Hörs TMC Chemie', 'Location' => 'Bu 45, TMC', 'seats' => 180, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Hörsaal A Chemie', 'Location' => 'MLKP 6', 'seats' => 660, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Hörsaal B Chemie', 'Location' => 'MLKP 6', 'seats' => 245, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Hörsaal C Chemie', 'Location' => 'MLKP 6', 'seats' => 156, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Hörsaal D Chemie', 'Location' => 'MLKP 6', 'seats' => 120, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'VMP 11 R 4', 'Location' => 'VMP 11', 'seats' => 81, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'VMP 9 H', 'Location' => 'VMP 9', 'seats' => 250, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Erzwiss H', 'Location' => 'VMP 8', 'seats' => 472, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Wiwi A', 'Location' => 'VMP 5', 'seats' => 248, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Wiwi B1', 'Location' => 'VMP 5', 'seats' => 137, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Wiwi B2', 'Location' => 'VMP 5', 'seats' => 95, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Phil A', 'Location' => 'VMP 6', 'seats' => 307, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Phil B', 'Location' => 'VMP 6', 'seats' => 223, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Phil C', 'Location' => 'VMP 6', 'seats' => 202, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Phil D', 'Location' => 'VMP 6', 'seats' => 303, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Phil E', 'Location' => 'VMP 6', 'seats' => 91, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Phil F', 'Location' => 'VMP 6', 'seats' => 91, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Phil G', 'Location' => 'VMP 6', 'seats' => 148, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'ESA A', 'Location' => 'ESA 1', 'seats' => 622, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'ESA B', 'Location' => 'ESA 1', 'seats' => 361, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'ESA C', 'Location' => 'ESA 1', 'seats' => 174, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'ESA H', 'Location' => 'ESA 1', 'seats' => 80, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'ESA J', 'Location' => 'ESA 1', 'seats' => 174, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'ESA K', 'Location' => 'ESA 1', 'seats' => 80, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'ESA M', 'Location' => 'ESA 1', 'seats' => 167, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'MBA HörS 030', 'Location' => 'MBA 60', 'seats' => 77, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'MBA HörS 233', 'Location' => 'MBA 60', 'seats' => 59, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 0],
				['name' => 'Audimax 1', 'Location' => 'VMP 4', 'seats' => 1164, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 1],
				['name' => 'Audimax 2', 'Location' => 'VMP 4', 'seats' => 510, 'roomtype_id' => 1, 'beamer' => 1, 'blackboard' => 1, 'overheadprojector' => 1, 'accessible' => 1],
		);
		DB::table('rooms')->insert($rooms);
	}
}